engines:
  duplication:
    enabled: true
    config:
      languages:
        php:
          mass_threshold: 40
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
    - "src/Linfo/**.php"
exclude_paths:
  - tests/
